const unsigned char WebSide[] = {
"<html>\r\n"
"<head>\r\n"
"<meta http-equiv=\"refresh\" content=\"5\">\r\n"
"<title>easyWEB - dynamic Webside</title>\r\n"
"</head>\r\n"
"\r\n"
"<body bgcolor=\"#3030A0\" text=\"#FFFF00\">\r\n"
"<p><b><font color=\"#FFFFFF\" size=\"6\"><i>Hello World!</i></font></b></p>\r\n"
"\r\n"
"<p><b>This is a dynamic website hosted by the embedded Webserver</b> <b>easyWEB.</b></p>\r\n"
"<p><b>Hardware:</b></p>\r\n"
"<ul>\r\n"
"<li><b>lpc43xx NXP Evaluation board. ARM M4 Cortex running EasyWeb</b></li>\r\n"
"<li><b>Embedded EMAC Ethernet Controller (New IP!)</b></li>\r\n"
"</ul>\r\n"
"\r\n"
"<p><b>A/D Converter Input 2 - POT1: AD8% </b></p>\r\n"
"\r\n"
"<table bgcolor=\"#ff0000\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<table width=\"AD7%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
"<tr><td bgcolor=\"#00ff00\">&nbsp;</td></tr>\r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"<table border=\"0\" width=\"540\">\r\n"
"<tr>\r\n"
"<td width=\"15%\">0V</td>\r\n"
"<td width=\"15%\">0.5V</td>\r\n"
"<td width=\"15%\">1V</td>\r\n"
"<td width=\"15%\">1.5V</td>\r\n"
"<td width=\"15%\">2V</td>\r\n"
"<td width=\"15%\">2.5V</td>\r\n"
"<td width=\"15%\">3V</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"<br><br><br><br>\r\n"
"<table border=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td width=\"10%\"></td>\r\n"
"<td width=\"45%\">\r\n"
"<table bgcolor=\"silver\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"250\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<p><b><font color=\"#FFFFFF\" size=\"6\"><i>Page Count: AD1%</i></font></b></p>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n"
"\r\n"};
