###############################################################################
# add library
#
OBJ += main.o

VPATH += FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)src

INCLUDE += -IFreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)inc

CFGFILES += FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)etc$(DIR)mtst01.oil			\
				FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)etc$(DIR)testsuite.oil				\
				FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)etc$(DIR)OpenDRV.oil					\
				FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)etc$(DIR)OpenGEN.oil					\
				FreeOSEK$(DIR)Os$(DIR)tst$(DIR)mtst$(DIR)mtst01$(DIR)etc$(DIR)seENC.oil

CLEAN += mtst01clean

mtst01clean :


