###############################################################################
#
# Copyright 2014, Mariano Cerdeiro
#
# This file is part of CIAA Firmware.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################

# library
LIBS 				+= update_common
# library path
update_common_PATH 		= $(ROOT_DIR)$(DS)modules$(DS)update$(DS)common
# library source path
update_common_SRC_PATH 		= $(update_common_PATH)$(DS)src
# library include path
update_common_INC_PATH 		= $(update_common_PATH)$(DS)inc
# library source files
update_common_SRC_FILES 	= $(wildcard $(update_common_SRC_PATH)$(DS)*.c)

# library
LIBS 				+= update_slave
# library path
update_slave_PATH 		= $(ROOT_DIR)$(DS)modules$(DS)update$(DS)slave
# library source path
update_slave_SRC_PATH 		= $(update_slave_PATH)$(DS)src
# library include path
update_slave_INC_PATH 		= $(update_slave_PATH)$(DS)inc
# library source files
update_slave_SRC_FILES 		= $(wildcard $(update_slave_SRC_PATH)$(DS)*.c)