###############################################################################
#
# Copyright 2014, ACSE & CADIEEL
#    ACSE   : http://www.sase.com.ar/asociacion-civil-sistemas-embebidos/ciaa/
#    CADIEEL: http://www.cadieel.org.ar
#
# This file is part of CIAA Firmware.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################
# Copy this file to Makefile.mine and set the variables.
#
# Makefile.mine will be included by the root make file but ignored by
# .gitignore.
#
# You can also remove this commentas lines.
#
# Please take into account to check and compare your Makefile.mine every time
# that Makefile.config is updated to be sure that you dont need to define new
# variables.
#
###############################################################################
# ARCH, CPUTYPE and CPU following are supported
# +--------------+---------------+----------------+--------------+
# |      ARCH    |    CPUTYPE    |      CPU       | COMPILER     |
# +--------------+---------------+----------------+--------------+
# | x86			  | ia32 			|                | gcc          |
# |              | ia64 			|                |              |
# +--------------+---------------+----------------+--------------+
# | cortexM4     | lpc43xx       | lpc4337        | gcc          |
# |              | k60_120       | mk60fx512vlq15 | gcc          |
# +--------------+---------------+----------------+--------------+
#
ARCH           = x86
CPUTYPE        = ia64
CPU            = none
COMPILER       = gcc
# Project
#
# Available projects are:
# examples/blinking				(example with rtos and posix)
# examples/blinking_base		(example without rtos and without posix)
# examples/blinking_wo_rtos 	(example with posix without rtos)
# examples/blinking_wo_posix	(example with rtos without rtos)
# examples/blinking_modbus		(example with rtos, posix and using modbus)
#
PROJECT ?= examples$(DS)blinking

