

#ifndef CIAAERRORSCODESYSTEM_H_
#define CIAAERRORSCODESYSTEM_H_

#define ciaaPOSIX_MINERRORCODE		-1
#define ciaaPOSIX_MAXERRORCODE		-1000

#define ciaaUART_MINERRORCODE			-1001
#define ciaaUART_MAXERRORCODE			-2000

#endif
