/**********************************************************************
* $Id$		eeprom.c			2011-06-02
*//**
* @file		eeprom.c
* @brief	Contains all functions support for EEPROM firmware library on
*			LPC18xx
* @version	1.0
* @date		02. June. 2011
* @author	NXP MCU SW Application Team
* 
* Copyright(C) 2011, NXP Semiconductor
* All rights reserved.
*
***********************************************************************
* Software that is described herein is for illustrative purposes only
* which provides customers with programming information regarding the
* products. This software is supplied "AS IS" without any warranties.
* NXP Semiconductors assumes no responsibility or liability for the
* use of the software, conveys no license or title under any patent,
* copyright, or mask work right to the product. NXP Semiconductors
* reserves the right to make changes in the software without
* notification. NXP Semiconductors also make no representation or
* warranty that such application will be suitable for the specified
* use without further testing or modification.
**********************************************************************/

/* Peripheral group ----------------------------------------------------------- */
/** @addtogroup EEPROM
 * @{
 */

/* Includes ------------------------------------------------------------------- */
#include "eeprom.h"

/* Public Functions ----------------------------------------------------------- */

/*********************************************************************//**
 * @brief 		Initial EEPROM
 * @param[in]	None
 * @return 		None
 **********************************************************************/
void EEPROM_Init(uint32_t eepromHz)
{
	LPC_EEPROM->PWRDWN = 0x0;
	/* EEPROM is automate turn on after reset */
	/* Setting clock:
	 * EEPROM required a 1500kHz. This clock is generated by dividing the
	 * system bus clock.
	 */
	
	 LPC_EEPROM->CLKDIV = eepromHz / 1500000; // 31 ;	//EEPROM clock=1500 KHz
	 LPC_EEPROM->RWSTATE = ((eepromHz / 28571429) << 8) | (eepromHz / 14285714); //(0x3 | 0x5<<8);	// Read waitstates.

	 LPC_EEPROM->WSTATE = ((eepromHz / 50000000) << 16) | ((eepromHz / 25000000) << 8) | (eepromHz / 100000000); // (0x2 | 0x3<<8 | 0x2<<16);	//EEPROM wait state register
}

/**
 * @}
 */

/* --------------------------------- End Of File ------------------------------ */

