##############################################################################
# add library
#
OPENOSEK_OBJ +=	Os_Internal_Arch_Cpu.o

VPATH		+=		FreeOSEK$(DIR)Os$(DIR)src$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
INCLUDE += 		-IFreeOSEK$(DIR)Os$(DIR)inc$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
